export const CONTROL_PLANE_FAILURE_CODES = {
  IDENTIFIER_EMPTY: 'OMP_CP_IDENTIFIER_EMPTY',
  IDENTIFIER_TOO_LONG: 'OMP_CP_IDENTIFIER_TOO_LONG',
  IDENTIFIER_PATH_TRAVERSAL: 'OMP_CP_IDENTIFIER_PATH_TRAVERSAL',
  IDENTIFIER_INVALID: 'OMP_CP_IDENTIFIER_INVALID',
  EMPTY_INPUT: 'OMP_CP_EMPTY_INPUT',
  INVALID_TIMESTAMP: 'OMP_CP_INVALID_TIMESTAMP',
  INVALID_LEASE_MS: 'OMP_CP_INVALID_LEASE_MS',
  TASK_NOT_FOUND: 'OMP_CP_TASK_NOT_FOUND',
  TASK_TERMINAL: 'OMP_CP_TASK_TERMINAL',
  TASK_DEPENDENCIES_UNRESOLVED: 'OMP_CP_TASK_DEPENDENCIES_UNRESOLVED',
  TASK_ALREADY_CLAIMED: 'OMP_CP_TASK_ALREADY_CLAIMED',
  TASK_CLAIM_MISSING: 'OMP_CP_TASK_CLAIM_MISSING',
  TASK_CLAIM_OWNER_MISMATCH: 'OMP_CP_TASK_CLAIM_OWNER_MISMATCH',
  TASK_CLAIM_TOKEN_MISMATCH: 'OMP_CP_TASK_CLAIM_TOKEN_MISMATCH',
  TASK_CLAIM_LEASE_EXPIRED: 'OMP_CP_TASK_CLAIM_LEASE_EXPIRED',
  TASK_LEASE_REASSIGNMENT_CONFLICT: 'OMP_CP_TASK_LEASE_REASSIGNMENT_CONFLICT',
  TASK_TRANSITION_FROM_MISMATCH: 'OMP_CP_TASK_TRANSITION_FROM_MISMATCH',
  TASK_COMPLETED_WITH_ERROR: 'OMP_CP_TASK_COMPLETED_WITH_ERROR',
  MAILBOX_BODY_EMPTY: 'OMP_CP_MAILBOX_BODY_EMPTY',
  MAILBOX_MESSAGE_NOT_FOUND: 'OMP_CP_MAILBOX_MESSAGE_NOT_FOUND',
  MAILBOX_RELOAD_FAILED: 'OMP_CP_MAILBOX_RELOAD_FAILED',
} as const;

export type ControlPlaneFailureCode =
  (typeof CONTROL_PLANE_FAILURE_CODES)[keyof typeof CONTROL_PLANE_FAILURE_CODES];

export type ControlPlaneFailureError = Error & {
  code: ControlPlaneFailureCode;
  reasonCode: ControlPlaneFailureCode;
};

export function createControlPlaneFailure(
  code: ControlPlaneFailureCode,
  message: string,
): ControlPlaneFailureError {
  const error = new Error(`[${code}] ${message}`) as ControlPlaneFailureError;
  error.name = 'ControlPlaneFailureError';
  error.code = code;
  error.reasonCode = code;
  return error;
}
